### ISSUE TITLE
Demo not providing location data when running in background. IOS

### ISSUE THREAD

**Issue by mrwrighty** [farfromrefug/nativescript-gps#11]
Built and running the demo on the iOS simulator, but app is not providing location data when the app is in the background.

Data stops as soon as app is moved to background.

How do I keep the app providing location data whilst in the background. (Not Closed)

**Comment by farfromrefug** [comment]
@mrwrighty totally normal the demo app project is not "setup" on iOS to work while in background. You need to look at iOS background gps tutorials

**Comment by mrwrighty** [comment]
Where can I find the tutorials the documentation looks pretty sketchy.

**Comment by farfromrefug** [comment]
@mrwrighty look on theweb ! this plugin is just a wrapper to the native side . you need to look at native tutorials + this plugin typings and you ll be able.to do almost anything. 
not all options are shared by iOS and android since the native behaves differently (documented in typings)

**Comment by liamcharmer** [comment]
Hello @mrwrighty  did you get a solution for this? i'm just about to do my search now for the answers but if you came across anything that would be great!

**Comment by mrwrighty** [comment]
No I didn't. When in the background the GPS refuses to run.

**Comment by mrwrighty** [comment]
If you find anything, please post here.

**Comment by liamcharmer** [comment]
@mrwrighty ah okay, have you searched anything at all??

**Comment by mrwrighty** [comment]
Yes I spent weeks trying to resolve this. I had previously used https://github.com/transistorsoft/nativescript-background-geolocation-lt which was a brilliant plugin, but the developer no longer supports Nativescript which is really frustrating. I've had to remove this function from my app until I can find a solution.

**Comment by liamcharmer** [comment]
@mrwrighty alrighty no worries, I guess I'll have a look. Im assuming what you have to do on GPS initialisation is to do a if check for Android and iOS and then apply the specific requirements for each browser to enable background requests.

**Comment by farfromrefug** [comment]
@mrwrighty @liamcharmer it works perfectly fine here. We have navigations running for hours if not days. I am not sure what your issue is. It mostly depends on the settings you use on iOS which is why i told you to look at native tutorials. 
In our case with use it for navigation (high speed gps) so we just need to define it as a background feature and it works.
It is different if you want like on GPS loc every hour. In this case my plugin might not even work for that on IOS

**Comment by liamcharmer** [comment]
@farfromrefug that's what i'm looking on now at the native side! (Just trying to find the place on how we define it as a background feature) -> Thank you though for the response sorry!!!

**Comment by farfromrefug** [comment]
@liamcharmer https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html
Look for UIBackgroundModes

**Comment by liamcharmer** [comment]
> Look for UIBackgroundModes

Awesome stuff! I've been looking at: 
https://developer.apple.com/documentation/corelocation/getting_the_user_s_location/handling_location_events_in_the_background but it didn't mention about UIBackgroundModes so my mistake! (I'm assuming their tickbox method is the same as info.plist)

so i've set 
```
<key>UIBackgroundModes</key>
<array>
	<string>location</string>
	<string>fetch</string>
</array>
<key>UIApplicationExitsOnSuspend</key>
<string>NO</string>
```

So lets hope I can get somewhere with this, Thank you!!!

**Comment by mrwrighty** [comment]
I have these settings in my info.plist file. Still no joy.

**Comment by liamcharmer** [comment]
@farfromrefug  i've got it working but with another library. However because of your instruction honestly you've helped so much! Sorry If i came across badly or anything!!!

**Comment by farfromrefug** [comment]
@mrwrighty How do you use it? we cant help you if you dont give more details...

**Comment by liamcharmer** [comment]
@mrwrighty  I used the nativescript-geolocation library

https://docs.nativescript.org/plugins/geolocation.html#properties 

* iosAllowsBackgroundLocationUpdates*

Clearly me and you are awful at reading documentation, because they have the property right there and instruct us to do info.plist update.

**Comment by liamcharmer** [comment]
@farfromrefug when i tried with this package, I had set the info.plist file and then literally had the same code as in the demo and didn't seem to work with me there.

**Comment by mrwrighty** [comment]
From my original post I ran the demo from the GitHub demo, and could not get background gps to work. I ran out of time and had to move to another project.
