### ISSUE TITLE
Android - isAuthorized method always returns false

### ISSUE THREAD

**Issue by sivo1981** [farfromrefug/nativescript-gps#24]
On Android with latest release method `isAuthorized` always returns `false` due to this line:

https://github.com/nativescript-community/gps/blob/13102756b38e5aa131d8b8ebf33afb15fb899939/src/gps/index.common.ts#L65

I have made output of variable `s`:

```
console.log('s', s)
s authorized

console.log('s[0]', s[0])
s[0] a
```

Looks like variable `s` returned from `check('location')` is not an array but a string.

Looking for a quick fix ... ty.

**Comment by farfromrefug** [comment]
@sivo1981 what version of the perms plugin are you using ? Latest ?

**Comment by sivo1981** [comment]
It's not the latest one. Could this be the problem?

**Comment by farfromrefug** [comment]
@sivo1981 yes it is. There was a broken build of perms

**Comment by sivo1981** [comment]
@farfromrefug working fine with latest perms plugin.
