### ISSUE TITLE
TypeError when calling function isEnabled

### ISSUE THREAD

**Issue by sivo1981** [farfromrefug/nativescript-gps#5]
After importing this plugin on NS7 for Android

`import * as gps from '@nativescript-community/gps'`
`gps.GPS.isEnabled()`

i'm getting this error when calling
`TypeError: _nativescript_community_gps__WEBPACK_IMPORTED_MODULE_7__.GPS.isEnabled is not a function`

**Comment by farfromrefug** [comment]
@sivo1981 `GPS` is class you must instantiate it first. I am sorry the doc is no good :s I have to do something about this...

**Comment by sivo1981** [comment]
@farfromrefug Working with `new gps.GPS()`.
