### ISSUE TITLE
Android getLastKnownLocation throws error

### ISSUE THREAD

**Issue by sivo1981** [farfromrefug/nativescript-gps#8]
√ Getting NativeScript components versions information...
√ Component nativescript has 7.1.2 version and is up to date.
√ Component @nativescript/core has 7.1.4 version and is up to date.   
√ Component @nativescript/ios has ^7.1.1 version and is up to date.   
√ Component @nativescript/android has 7.0.1 version and is up to date.

"@nativescript-community/gps": "^2.1.5"

When calling getLastKnownLocation error `Cannot read property 'getTime' of null` is thrown. Variable `tempLocation` is null.

https://github.com/nativescript-community/gps/blob/44d3384d02b50c5bde623b8b208c94242f2eb3d5/src/gps.android.ts#L447

**Comment by farfromrefug** [comment]
@sivo1981 fixed in 2.1.7.
Thanks for the detailed report!

**Comment by sivo1981** [comment]
@farfromrefug works great. Thanks for a quick fix.
